webtalk_init -webtalk_dir D:/HSD_SNU_2021/labs/project_v0_mid/project_v0_mid.sim/sim_1/behav/xsim/xsim.dir/tb_pe_array_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Apr 24 18:14:26 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ba2a894f-e3fd-4f6b-af08-1a29803d931d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4df68a34e1d948fc80e0cdfdd379e314" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2195 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "13 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "6.69_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "127044_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2161891589 -regid "" -xml D:/HSD_SNU_2021/labs/project_v0_mid/project_v0_mid.sim/sim_1/behav/xsim/xsim.dir/tb_pe_array_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/HSD_SNU_2021/labs/project_v0_mid/project_v0_mid.sim/sim_1/behav/xsim/xsim.dir/tb_pe_array_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/HSD_SNU_2021/labs/project_v0_mid/project_v0_mid.sim/sim_1/behav/xsim/xsim.dir/tb_pe_array_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
