# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/HSD_SNU_2021/labs/project_v0_mid/project_v0_mid.cache/wt [current_project]
set_property parent.project_path D:/HSD_SNU_2021/labs/project_v0_mid/project_v0_mid.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem D:/HSD_SNU_2021/labs/project_v0_mid/project_v0_mid.srcs/sources_1/new/input.txt
read_verilog -library xil_defaultlib {
  D:/HSD_SNU_2021/labs/project_v0_mid/project_v0_mid.srcs/sources_1/new/my_pe.v
  D:/HSD_SNU_2021/labs/project_v0_mid/project_v0_mid.srcs/sources_1/new/my_pe_array.v
  D:/HSD_SNU_2021/labs/project_v0_mid/project_v0_mid.srcs/sources_1/new/tb_pe_array.v
}
read_ip -quiet D:/HSD_SNU_2021/labs/project_v0_mid/project_v0_mid.srcs/sources_1/ip/floating_point_MAC/floating_point_MAC.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top tb_pe_array -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef tb_pe_array.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file tb_pe_array_utilization_synth.rpt -pb tb_pe_array_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
